### ISSUE TITLE
Could you provide the used PnP script in you paper?

### ISSUE THREAD

**Issue by Tomas-Lee** [zlthinker/KFNet#2]
After I run your SCoordNet in my dataset, I found that almost 60% of Scene coordinate error is under 2cm, It's fine. 
but when I use these correspondences in npy format output to compute camera pose, the pose fluctuate greatly.  Average pose trans_part =50.7cm, It is so high. I don't know why?
So could you provide the used PnP scrpt in your paper? what I use is cv2.solvePnPRansac() function.
Thanks very much.

**Comment by somanyunknowns** [comment]
> After I run your SCoordNet in my dataset, I found that almost 60% of Scene coordinate error is under 2cm, It's fine.
> but when I use these correspondences in npy format output to compute camera pose, the pose fluctuate greatly. Average pose trans_part =50.7cm, It is so high. I don't know why?
> So could you provide the used PnP scrpt in your paper? what I use is cv2.solvePnPRansac() function.
> Thanks very much.

Hi, Tomas,

I have tested it with my own PnP program and the results are reasonable. Are you using the correct intrinsics? The focal is 525 and the principle points are (320, 240).

**Comment by XinWu98** [comment]
Hi, I notice that the uploaded file PnP.zip couldn't be extracted correctly?

**Comment by somanyunknowns** [comment]
> Hi, I notice that the uploaded file PnP.zip couldn't be extracted correctly?

Hi, you may need to install git-lfs first and clone again, since PnP.zip is stored as LFS in the repo.

**Comment by XinWu98** [comment]
> > Hi, I notice that the uploaded file PnP.zip couldn't be extracted correctly?
> 
> Hi, you may need to install git-lfs first and clone again, since PnP.zip is stored as LFS in the repo.

Yes, it works. Thanks!
