### ISSUE TITLE
what's the content in image_file.txt and label_list.txt?

### ISSUE THREAD

**Issue by qzhai** [zlthinker/KFNet#5]
Hi Lei,

I just want to play your code and I am not similar to the 7Scenes, I have few questions about the code.

1. I guess image_file.txt and label_list.txt are listed under the 'input_folder', but where can I find those files? as I just find TrainSplit.txt and TestSplit.txt.

2.how to use the prepared input label map files you provided in the Google Drive?

Thank you.

**Comment by wolf943134497** [comment]
> Hi Lei,
> 
> I just want to play your code and I am not similar to the 7Scenes, I have few questions about the code.
> 
> 1. I guess image_file.txt and label_list.txt are listed under the 'input_folder', but where can I find those files? as I just find TrainSplit.txt and TestSplit.txt.
> 
> 2.how to use the prepared input label map files you provided in the Google Drive?
> 
> Thank you.

Hi, @qiangzuestc   How to get the image_file.txt? I just find TrainSplit.txt and TestSplit.txt. Thanks!

**Comment by somanyunknowns** [comment]
> > Hi Lei,
> > I just want to play your code and I am not similar to the 7Scenes, I have few questions about the code.
> > 
> > 1. I guess image_file.txt and label_list.txt are listed under the 'input_folder', but where can I find those files? as I just find TrainSplit.txt and TestSplit.txt.
> > 
> > 2.how to use the prepared input label map files you provided in the Google Drive?
> > Thank you.
> 
> Hi, @qiangzuestc How to get the image_file.txt? I just find TrainSplit.txt and TestSplit.txt. Thanks!

Hi, there. The image_file.txt is just the list of paths of images for training or testing. You can generate it yourself.
